### ISSUE TITLE
build-constraints.yaml RFC: Move grouping/formatting/comments into the YAML structure

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/curator#22]
When curator parsers build-constraints.yaml (using the `yaml` package)
we lose information about grouping/formatting/comments. This means
that views (#21) are missing information.

If we add this information to the YAML structure we would be able to add some cool tooling, like:
* List all mentions of a github issue
* List all packages by github issues
* List all packages with a "GHC 9" comment
* (assuming github integration) Check if a referenced issues has been
  closed (we could enrich the output if you pass `--github`)

This would also allow us to have curator commands that modify the
file, e.g. `curator re-enable Agda`, `curator upper-bound "#5587"
"network<3.1.2.0"`. However, this requires us to stick to this new
format and never add comments. So we'd probably need to wait with this
to make sure that the new format is expressive enough and not
cumbersome, so we don't feel the need/urge to escape it.

We don't need to touch the maintainer area much for this. A new
maintainer adding a package can still do it in the exact same way, but
we'd want to be able to add comments / issue links for a package.

@DanBurton wrote in #20, this may still apply:

> One maintainer downside to this is that the place that maintainers
> modify to add packages looks more complex. Instead of just listing
> their packages under their name, they now see a bunch of fields and
> need to worry about which field names are valid and what they mean
> and whether they are expected to customize these fields for each of
> their packages. For the uninitiated it makes adding your own
> packages appear to be less approachable.

@DanBurton do you think this would still be an issue if maintainers
can add packages as they do today? We could have some example under
"Add your package" in README.md to clarify that this is the default:

> Example of adding packages:
> "My Name <myemail@example.com> @mygithubhandle":
>    - package1
>    - package2

We should be able to add do this package by package / constraint by constraint, to not have to do a big migration. We can keep using comments and linebreaks for grouping as an escape hatch as long as we don't have scripts that re-write the file.

Format examples:

```yaml
# supercedes "Stackage upper bounds", can also be used for GHC upgrades and other batch operations.
# Doesn't need to be in a separate top level entry, but it feels cleaner to me.
constraints:
  "optparse-applicative 0.16":
     - issue: https://github.com/commercialhaskell/stackage/issues/5597
     - comment: Hello
     - constraints: # `constraints:` can be optional if it's the only property
       - optparse-applicative < 0.16
       - optparse-generic < 1.4
       - turtle < 1.5.21
  "GHC 9":
    - Agda < 0
    - cabal-rpm < 0
    - entropy < 0
 ```

```yaml
skipped-tests:
  "Outdated dependencies":
    comment: These can periodically be checked for updates.
    packages: # `packages:` can be optional if it's the only property
      - package: time-compat 
        comment: base-compat 0.11
      - package: http-media
        comment: base-4.13
      - package: simple-vec
        comment: ghc 8.10
      - static-text # `package:` can be optional if it's the only property
      - monad-par
      - package: avers
        comment: via base16-bytestring
        issue: https://github.com/commercialhaskell/stackage/issues/5649
```
