### ISSUE TITLE
LTS releases dropping packages unintentionally

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/curator#5]
In LTS 14.10 the following were unintentionally dropped:

* replace-attoparsec-1.0.2.0
* replace-megaparsec-1.1.4.0
* servant-rawm-0.3.2.0

https://www.stackage.org/diff/lts-14.9/lts-14.10

We should look into how this is possible; it is likely a curator bug.

**Comment by jkachmar** [comment]
I've manually added these back to LTS 14.11, but I haven't gotten a chance to dig through the curator to see how this could have happened in the first place.

**Comment by bergmark** [comment]
Happened with more packages https://www.stackage.org/diff/lts-14.12/lts-14.13

**Comment by bergmark** [comment]
Looking at constraints.yaml it says
```
  amazonka-apigateway:
    maintainers:
    - Blocked per http-client-0.6
    - Brendan Hay <brendan.g.hay@gmail.com> @brendanhay
    source:
      range: <0
      revisions: use-revisions
      type: hackage
```
So was this removed intentionally? How/when did `Blocked per http-client-0.6` end up there?

**Comment by jkachmar** [comment]
As discussed in the curators chat today, is it possible that some packages being dropped could be related to the fact that `range` is only parsed if it's within a `source` block?

e.g. The following would successfully parse, but the range field would be ignored:
```yaml
foo:
  maintainers:
  - Joe Kachmar <jkachmar@example.com> @jkachmar 
  range: <0
  source:
    revisions: use-revisions
    type: hackage
```
This is due to the fact that the `PackageConstraints` parser won't explicitly fail if it has an extra field, along with the `HackageSource` parser (rightfully) accepting `range` as an optional field:

https://github.com/commercialhaskell/curator/blob/96b381ebc502dc28e6bfcc452617d8f02399369f/src/Curator/Types.hs#L84-L94

https://github.com/commercialhaskell/curator/blob/96b381ebc502dc28e6bfcc452617d8f02399369f/src/Curator/Types.hs#L123
